### ISSUE TITLE
Keras-contrib dependency fails on master

### ISSUE THREAD

**Issue by miesav** [rsanchezgarc/deepEMhancer#9]
Hi,

when trying to install with pip on a python3 mvenv keras-contrib cannot be satisfied:

```
Collecting keras-contrib@ git+https://github.com/keras-team/keras-contrib.git@3fc5ef709e061416f4bc8a92ca3750c824b5d2b0 (from deepEMhancer==0.13)
  Could not find a version that satisfies the requirement keras-contrib@ git+https://github.com/keras-team/keras-contrib.git@3fc5ef709e061416f4bc8a92ca3750c824b5d2b0 (from deepEMhancer==0.13) (from versions: )
No matching distribution found for keras-contrib@ git+https://github.com/keras-team/keras-contrib.git@3fc5ef709e061416f4bc8a92ca3750c824b5d2b0 (from deepEMhancer==0.13)
```

keras-contrib seems deprecated in favour of https://github.com/tensorflow/addons.

Kind regards.

**Comment by rsanchezgarc** [comment]
Hi,

I am not been able to reproduce your issue.

Are you using `python -m pip install .` to install deepEMhancer ?

If not, could you provide the detailed list of commands you are using and the details about your machine. 

Thank you very much. 

Ruben

**Comment by rsanchezgarc** [comment]
Hi @schloegl, could you try to use the TensorFlow version 2 branch (https://github.com/rsanchezgarc/deepEMhancer#tensorflow-2-installation)?

**Comment by schloegl** [comment]
I tried a number of things but always ended up in a dead end. 

The requirements in setup.py are just too outdated, and do not match to python/3.9.7, cuda/11.2.2, cudnn/8.1.0. I could not even install the requirements of 
 ```
 'numpy==1.16.*',
  'scikit-image==0.15.*',

```

The latest thing I tried is to avoid the suggested versions and let pip find a suitable combination, and I had to leave out keras-contrib . 

```
python3 -m venv $PREFIX
source ${PREFIX}/bin/activate
pip install -U pip
pip install Cython
pip install scipy numpy tensorflow-gpu keras pandas mrcfile requests tqdm keras-radam 
DEEPEMHANCER_INSTALL_GPU=True python -m pip install --no-deps . 

```
At runtime, it failed with 

```
$PREFIX/lib/python3.9/site-packages/deepEMhancer/applyProcessVol/processVol.py", line 3, in <module>
    from skimage.util import pad
ModuleNotFoundError: No module named 'skimage'
```
After installing scikit-image, it fails with:

```
/20211217/lib/python3.9/site-packages/deepEMhancer/applyProcessVol/processVol.py", line 3, in <module>
    from skimage.util import pad
ImportError: cannot import name 'pad' from 'skimage.util'
```

My conclusion, the tf2 branch is just not ready yet, and nobody has tested this on a recent version of python.

**Comment by rsanchezgarc** [comment]
@schloegl . The tf2 branch is the one I have installed on my laptop. It works with python 3.8 but I haven't checked python 3.9. I maintain this repo in my spare time, which unfortunately is not abundant.

May I ask you why you don't try to create a conda environment using python 3.8 and install it there?

If you want to investigate what are the changes required to make it compatible with python 3.9 I will be happy to include them. I guess that the pad problem can be solved using numpy.pad instead

**Comment by schloegl** [comment]
I prefer using pypi over conda, so I tried this first. In the meantime, I've installed the conda version, which seems to work. 
I'm just trying to give feedback to an issue that was rised by somebody else, and to your suggestions above.
